// Exportar todos os templates de email
export * from './welcome'
export * from './reset_password'
export * from './stock_low'
export * from './notification'
export * from './store_invite'
export * from './email_verification'
export * from './initial_password'
export * from './schedule-approval-request'
export * from './schedule-approved'
export * from './schedule-rejected'
